spring:
  datasource:
    url: jdbc:sqlserver://ehr-server.database.windows.net:1433;database=EHR;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: Amer1
    password: Egypt25jan_123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9090

